/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Character: typeof import('./src/components/character/Character.vue')['default']
    CreateIcon: typeof import('./src/components/navbar/icons/CreateIcon.vue')['default']
    FriendIcon: typeof import('./src/components/navbar/icons/FriendIcon.vue')['default']
    HomepageIcon: typeof import('./src/components/navbar/icons/HomepageIcon.vue')['default']
    MenuIcon: typeof import('./src/components/navbar/icons/MenuIcon.vue')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/navbar/icons/SearchIcon.vue')['default']
    UserLogoutIcon: typeof import('./src/components/navbar/icons/UserLogoutIcon.vue')['default']
    UserMenu: typeof import('./src/components/navbar/UserMenu.vue')['default']
    UserProfileIcon: typeof import('./src/components/navbar/icons/UserProfileIcon.vue')['default']
    UserSpaceIndex: typeof import('./src/components/navbar/icons/UserSpaceIndex.vue')['default']
  }
}
