# Generated by Django 6.0.1 on 2026-06-05 12:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 12, 18, 28, 901561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 12, 18, 28, 901574, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(max_length=500)),
                ('input', models.TextField(max_length=500)),
                ('output', models.TextField(max_length=500)),
                ('input_token', models.IntegerField(default=0)),
                ('output_token', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2026, 6, 5, 12, 18, 28, 901819, tzinfo=datetime.timezone.utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2026, 6, 5, 12, 18, 28, 901825, tzinfo=datetime.timezone.utc))),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.friend')),
            ],
        ),
    ]
