# Generated by Django 6.0.1 on 2026-07-15 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_friend_create_time_alter_friend_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
