# Generated by Django 6.0.1 on 2026-07-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_message_total_tokens_alter_friend_create_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='input_token',
            new_name='input_tokens',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='output_token',
            new_name='output_tokens',
        ),
    ]
